# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-04 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='po',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='target_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
