# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-06 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
