# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-06 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_project_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
