# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-07 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20171206_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='unit_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='units_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(10, 'Low'), (20, 'Medium'), (30, 'High'), (40, 'Top Urgent')], default=10),
        ),
    ]
