# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-30 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True)),
                ('required_date', models.DateField()),
                ('number', models.CharField(default='00000', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField()),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.IntegerField(choices=[(10, 'Low'), (20, 'Medium'), (30, 'High'), (40, 'Top Urgent'), (50, 'Someone are dying')], default=10)),
                ('approved', models.IntegerField(choices=[(0, 'Pending'), (1, 'Declined'), (2, 'Approved'), (3, 'Completed')], default=0)),
                ('completed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
