# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-31 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_fundsrequestapprovallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsrequest',
            name='po',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
