# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-27 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20171101_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsrequest',
            name='payment_priority',
            field=models.IntegerField(default=1),
        ),
    ]
