# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-28 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_fundsrequest_payment_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundsrequest',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
