# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-15 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='index',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='files_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
