# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-15 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0002_auto_20170615_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
