# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-20 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0003_auto_20170615_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelhistory',
            name='designer',
        ),
        migrations.DeleteModel(
            name='ModelHistory',
        ),
    ]
