# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-20 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0005_modelhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthistory',
            name='designers',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='lead_designer',
        ),
        migrations.DeleteModel(
            name='ProjectHistory',
        ),
    ]
