# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-28 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0009_request_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
