# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-11 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0013_auto_20170911_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestapprovallog',
            name='dated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2000, 1, 1, 1, 11, 11, 333000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
