# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-31 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0014_requestapprovallog_dated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='manager_approved',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Declined'), (2, 'Approved'), (3, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='owner_approved',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Declined'), (2, 'Approved'), (3, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='requestapprovallog',
            name='result',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Declined'), (2, 'Approved'), (3, 'Completed')], default=0),
        ),
    ]
